# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: Analyze with ShiftLeft NG SAST on Windows

on:
  pull_request:
  workflow_dispatch:

jobs:
  Inspect-Win-Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft cli
      run: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile sl.zip
        Expand-Archive -Path sl.zip -DestinationPath .
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Analyze with NG SAST
      run: |
        .\sl analyze --force --app juice-shop-win --tag branch=${GITHUB_REF} --wait --verbose --js --cpg . -- --with-tests --include-configs --exclude node_modules,vagrant,dist,data/static,build
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
